### ISSUE TITLE
Скоратить проверку

### ISSUE THREAD

**Issue by casa7x** [Tatsianazhylevich/Lesson-15#2]
https://github.com/Tatsianazhylevich/Lesson-15/blob/d27c1516da84d5ddab2e5a679e63824fc013cf5a/script.js#L13

Здесь не обязательно строгое сравнение на true, можно просто оставить проверку на наличие, ведь false и так возвращает отрицательное значение. Внутри скобок и так всё приводится к логическому типу)

**Comment by Tatsianazhylevich** [comment]
Ну вроде бы выполнила))
